import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final data = jsonDecode(File('assets/data/discover.json').readAsStringSync());
  final compact = jsonEncode(data);
  final output =
      "// Generated by scripts/generate_discover_seed.dart. Do not edit.\n"
      "part of '../main.dart';\n\nconst discoverSeedJson = r'''$compact''';\n";
  final target = File('lib/discover/seed_data.dart');
  if (args.contains('--check')) {
    if (!target.existsSync() || target.readAsStringSync().replaceAll('\r\n', '\n') != output) {
      stderr.writeln(
          'Discover seed is outdated. Run dart run scripts/generate_discover_seed.dart');
      exitCode = 1;
    }
  } else {
    target.writeAsStringSync(output);
  }
}
