import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final source = File('assets/data/discover.json');
  if (!source.existsSync()) {
    stderr.writeln('Missing assets/data/discover.json');
    exitCode = 1;
    return;
  }

  final raw = source.readAsStringSync();
  final catalog = jsonDecode(raw) as Map<String, dynamic>;
  final entries = (catalog['entries'] as List?) ?? const [];
  final restaurants = entries
      .where((e) =>
          e is Map<String, dynamic> && e['category'] == 'Restoranlar')
      .length;

  // The bundled seed must mirror the live Discover catalog exactly. Rebuilding
  // restaurant data from separate chunk files caused Codemagic to silently drop
  // restaurants_5.json and shrink the offline catalog from 50 to 40 entries.
  if (restaurants < 50) {
    stderr.writeln(
        'Discover catalog regression: expected at least 50 restaurants, found $restaurants.');
    exitCode = 1;
    return;
  }

  final compact = jsonEncode(catalog);
  final output =
      "// Generated by scripts/generate_discover_seed.dart. Do not edit.\n"
      "part of '../main.dart';\n\nconst discoverSeedJson = r'''$compact''';\n";

  final target = File('lib/discover/seed_data.dart');
  if (args.contains('--check')) {
    if (!target.existsSync() ||
        target.readAsStringSync().replaceAll('\r\n', '\n') != output) {
      stderr.writeln(
          'Discover seed is outdated. Run dart run scripts/generate_discover_seed.dart');
      exitCode = 1;
    }
  } else {
    target.writeAsStringSync(output);
    stdout.writeln(
        'Discover seed generated from live catalog: $restaurants restaurants, ${entries.length} total entries.');
  }
}
