import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final base = jsonDecode(File('assets/data/discover.json').readAsStringSync())
      as Map<String, dynamic>;
  final baseEntries = (base['entries'] as List)
      .where((e) => (e as Map<String, dynamic>)['category'] != 'Restoranlar')
      .toList();

  final restaurants = <dynamic>[];
  for (var i = 1; i <= 4; i++) {
    final chunk = jsonDecode(
        File('assets/data/restaurants_$i.json').readAsStringSync())
        as Map<String, dynamic>;
    restaurants.addAll(chunk['entries'] as List);
  }

  final merged = <String, dynamic>{
    ...base,
    'revision': 2,
    'updatedAt': '2026-09-07T17:30:00Z',
    'entries': [...restaurants, ...baseEntries],
  };

  final compact = jsonEncode(merged);
  final output =
      "// Generated by scripts/generate_discover_seed.dart. Do not edit.\n"
      "part of '../main.dart';\n\nconst discoverSeedJson = r'''$compact''';\n";
  final target = File('lib/discover/seed_data.dart');
  if (args.contains('--check')) {
    if (!target.existsSync() ||
        target.readAsStringSync().replaceAll('\r\n', '\n') != output) {
      stderr.writeln(
          'Discover seed is outdated. Run dart run scripts/generate_discover_seed.dart');
      exitCode = 1;
    }
  } else {
    target.writeAsStringSync(output);
  }
}
