"""Restore brand assets, export compliance, and generated app wiring."""
import base64
import json
import plistlib
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parent.parent
logo = root / 'assets/images/logo.png'
logo.write_bytes(base64.b64decode((root / 'assets/images/logo.b64').read_text(), validate=True))
if not logo.read_bytes().startswith(b'\x89PNG\r\n\x1a\n'):
    raise SystemExit('Invalid logo PNG')
assets = root / 'ios/Runner/Assets.xcassets'
for name in ('AppIcon.appiconset', 'LaunchImage.imageset'):
    folder = assets / name
    manifest = folder / 'Contents.json'
    if not manifest.exists():
        raise SystemExit(f'Missing generated asset catalog: {manifest}')
    data = json.loads(manifest.read_text())
    for index, entry in enumerate(data['images']):
        scale = float(entry.get('scale', '1x').rstrip('x'))
        size = round(float(entry.get('size', '160x160').split('x')[0]) * scale)
        filename = entry.get('filename', f'brand-{index}.png')
        entry['filename'] = filename
        subprocess.run(['sips', '-z', str(size), str(size), str(logo), '--out', str(folder / filename)], check=True)
    manifest.write_text(json.dumps(data, indent=2) + '\n')

# App Store Connect export-compliance prompt.
info_plist = root / 'ios/Runner/Info.plist'
if not info_plist.exists():
    raise SystemExit(f'Missing generated Info.plist: {info_plist}')
with info_plist.open('rb') as f:
    info = plistlib.load(f)
info['ITSAppUsesNonExemptEncryption'] = False
with info_plist.open('wb') as f:
    plistlib.dump(info, f, fmt=plistlib.FMT_XML, sort_keys=False)

# The iOS project is regenerated by Codemagic. Keep the Guide data and the
# visual Guide UI wired into main.dart on every clean checkout.
main_dart = root / 'lib/main.dart'
main = main_dart.read_text()
anchor = "part 'discover/seed_data.dart';"
if anchor not in main:
    raise SystemExit('Could not find Dart part-file anchor')
for part_line in (
    "part 'guide/premium_guide.dart';",
    "part 'guide/visual_guide.dart';",
):
    if part_line not in main:
        main = main.replace(anchor, anchor + '\n' + part_line, 1)

# Only the Rehber destination is replaced; the other four tabs stay untouched.
main = main.replace(
    'HomePage(), DiscoverPage(), CommunityPage(), GuidePage(), ProfilePage()',
    'HomePage(), DiscoverPage(), CommunityPage(), VisualGuidePage(), ProfilePage()',
    1,
)
main = main.replace(
    'HomePage(), DiscoverPage(), CommunityPage(), PremiumGuidePage(), ProfilePage()',
    'HomePage(), DiscoverPage(), CommunityPage(), VisualGuidePage(), ProfilePage()',
    1,
)
main_dart.write_text(main)

# Defensive compatibility cleanup for icon/font constants across Flutter stable.
guide = root / 'lib/guide/premium_guide.dart'
if not guide.exists():
    raise SystemExit(f'Missing premium guide: {guide}')
g = guide.read_text()
g = g.replace('Icons.family_restroom_outlined', 'Icons.family_restroom')
g = g.replace('Icons.directions_car_filled_outlined', 'Icons.directions_car_outlined')
g = g.replace('Icons.work_outline_rounded', 'Icons.work_outline')
g = g.replace('FontWeight.w650', 'FontWeight.w600')
# Repair the two missing Container closing parentheses in the compact legacy card.
g = g.replace(
    "child: Text(article.category, style: const TextStyle(fontSize: 9.5, fontWeight: FontWeight.w700)), Container(",
    "child: Text(article.category, style: const TextStyle(fontSize: 9.5, fontWeight: FontWeight.w700))), Container(")
g = g.replace(
    "child: Text('${article.links.length} resmî bağlantı', style: const TextStyle(fontSize: 9.5, fontWeight: FontWeight.w700))]),",
    "child: Text('${article.links.length} resmî bağlantı', style: const TextStyle(fontSize: 9.5, fontWeight: FontWeight.w700)))]),")
guide.write_text(g)

visual = root / 'lib/guide/visual_guide.dart'
if not visual.exists():
    raise SystemExit(f'Missing visual guide: {visual}')
v = visual.read_text().replace('FontWeight.w650', 'FontWeight.w600')

# Responsive fixes validated against the 393px iPhone widget-test viewport.
# 1) Give the image hero enough vertical room for the Turkish copy.
v = v.replace(
    "child: SizedBox(\n            height: 260,\n            child: Stack(",
    "child: SizedBox(\n            height: 282,\n            child: Stack(",
    1,
)

# 2) Keep the hero CTA row inside narrow iPhone widths. The label flexes and
# ellipsizes instead of pushing the circular arrow outside the card.
hero_row_old = """                          const Text('Adım adım yol haritası', style: TextStyle(color: Colors.white70, fontSize: 11, fontWeight: FontWeight.w600)),
                          const Spacer(),
                          Container(
                            width: 38,"""
hero_row_new = """                          const Expanded(
                            child: Text(
                              'Adım adım yol haritası',
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: TextStyle(color: Colors.white70, fontSize: 11, fontWeight: FontWeight.w600),
                            ),
                          ),
                          const SizedBox(width: 8),
                          Container(
                            width: 38,"""
if hero_row_old not in v:
    raise SystemExit('Visual Guide hero CTA layout anchor not found')
v = v.replace(hero_row_old, hero_row_new, 1)

# 3) Flutter Container rejects negative margins. The journey hero stays
# aligned to the page padding rather than using a web-style full-bleed trick.
journey_margin_old = "margin: const EdgeInsets.fromLTRB(-18, 0, -18, 16),"
journey_margin_new = "margin: const EdgeInsets.only(bottom: 16),"
if journey_margin_old not in v:
    raise SystemExit('Visual Guide journey margin anchor not found')
v = v.replace(journey_margin_old, journey_margin_new, 1)

visual.write_text(v)

print('Brand assets, export compliance and responsive visual premium Guide wiring prepared.')
