"""Restore brand assets, export compliance, and generated app wiring."""
import base64
import json
import plistlib
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parent.parent
logo = root / 'assets/images/logo.png'
logo.write_bytes(base64.b64decode((root / 'assets/images/logo.b64').read_text(), validate=True))
if not logo.read_bytes().startswith(b'\x89PNG\r\n\x1a\n'):
    raise SystemExit('Invalid logo PNG')
assets = root / 'ios/Runner/Assets.xcassets'
for name in ('AppIcon.appiconset', 'LaunchImage.imageset'):
    folder = assets / name
    manifest = folder / 'Contents.json'
    if not manifest.exists():
        raise SystemExit(f'Missing generated asset catalog: {manifest}')
    data = json.loads(manifest.read_text())
    for index, entry in enumerate(data['images']):
        scale = float(entry.get('scale', '1x').rstrip('x'))
        size = round(float(entry.get('size', '160x160').split('x')[0]) * scale)
        filename = entry.get('filename', f'brand-{index}.png')
        entry['filename'] = filename
        subprocess.run(['sips', '-z', str(size), str(size), str(logo), '--out', str(folder / filename)], check=True)
    manifest.write_text(json.dumps(data, indent=2) + '\n')

# App Store Connect export-compliance prompt.
info_plist = root / 'ios/Runner/Info.plist'
if not info_plist.exists():
    raise SystemExit(f'Missing generated Info.plist: {info_plist}')
with info_plist.open('rb') as f:
    info = plistlib.load(f)
info['ITSAppUsesNonExemptEncryption'] = False
with info_plist.open('wb') as f:
    plistlib.dump(info, f, fmt=plistlib.FMT_XML, sort_keys=False)

# The iOS project is regenerated by Codemagic. Keep the premium Guide library
# wired into main.dart on every clean checkout without touching unrelated UI.
main_dart = root / 'lib/main.dart'
main = main_dart.read_text()
part_line = "part 'guide/premium_guide.dart';"
if part_line not in main:
    anchor = "part 'discover/seed_data.dart';"
    if anchor not in main:
        raise SystemExit('Could not find Dart part-file anchor')
    main = main.replace(anchor, anchor + '\n' + part_line, 1)
main = main.replace('HomePage(), DiscoverPage(), CommunityPage(), GuidePage(), ProfilePage()',
                    'HomePage(), DiscoverPage(), CommunityPage(), PremiumGuidePage(), ProfilePage()', 1)
main_dart.write_text(main)

# Defensive compatibility cleanup for icon/font constants across Flutter stable.
guide = root / 'lib/guide/premium_guide.dart'
if not guide.exists():
    raise SystemExit(f'Missing premium guide: {guide}')
g = guide.read_text()
g = g.replace('Icons.family_restroom_outlined', 'Icons.family_restroom')
g = g.replace('Icons.directions_car_filled_outlined', 'Icons.directions_car_outlined')
g = g.replace('Icons.work_outline_rounded', 'Icons.work_outline')
g = g.replace('FontWeight.w650', 'FontWeight.w600')
guide.write_text(g)

print('Brand assets, export compliance and premium Guide wiring prepared.')
